# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 15, 32, 20, 770041, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 15, 33, 2, 856814, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
