# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160314_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 15, 42, 3, 853582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 15, 42, 3, 853542, tzinfo=utc)),
        ),
    ]
