# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20160314_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
